# Base image for the runtime environment
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8083

# Build image for compiling the code
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["./Contatos.AlteracaoService.csproj", "Contatos.AlteracaoService/"]
RUN dotnet restore "./Contatos.AlteracaoService/Contatos.AlteracaoService.csproj"
WORKDIR "/src/Contatos.AlteracaoService"
COPY . .
RUN dotnet build "./Contatos.AlteracaoService.csproj" -c $BUILD_CONFIGURATION -o /app/build

# Publish image for creating the final application
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./Contatos.AlteracaoService.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# Final image for running the application
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Contatos.AlteracaoService.dll"]