{
 "title": "FIAP Fase 2 - PosTech",
 "time": { "from": "2024-07-13T05:04:02.957Z", "to": "2024-07-13T05:07:01.298Z" },
 "panels": [
  { "title": "Servidor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uso de CPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_runtime_cpu_usage * 100", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uso de CPU",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 5, "y": 1 },
   "targets": [
    { "expr": "system_runtime_cpu_usage", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Uso de Memória (dotnet)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mb" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes / 1048576",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "API (tempo médio de resposta)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Autenticação",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_request_duration_seconds_bucket{controller=\"Autenticacao\", code=\"200\"}[24h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_request_duration_seconds_bucket{endpoint=\"Cache\", code=\"200\"}[24h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Contatos",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_request_duration_seconds_bucket{endpoint=\"Contatos\", code=\"200\"}[24h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Regiões",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_request_duration_seconds_bucket{endpoint=\"Regioes\", code=\"200\"}[24h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Requisiões e Endpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Requisições API",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_received_total{instance=\"contatosapi:8080\", code=\"200\"})",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "sum(http_requests_received_total{instance=\"contatosapi:8080\", code=\"401\"})",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "sum(http_requests_received_total{instance=\"contatosapi:8080\", code=\"500\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Requisições (total)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 7, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_received_total{instance=\"contatosapi:8080\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Contatos (requisiões)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_received_total{instance=\"contatosapi:8080\", controller=\"Contatos\"}",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Requisições 200 (qntd)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 7, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_received_total{instance=\"contatosapi:8080\", code=\"200\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requisições 401 (qntd)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 7, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_received_total{instance=\"contatosapi:8080\", code=\"401\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requisições 500 (qntd)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 7, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_received_total{instance=\"contatosapi:8080\", code=\"500\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}