{
 "title": "Monitoramento de Serviços - Contatos",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Inclusão Service",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job='Contatos.CadastroService-read-http'}"
    }
   ]
  },
  {
   "title": "Alteracao Service",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job='Contatos.AlteracaoService-read-http'}"
    }
   ]
  },
  {
   "title": "Exclusão Service",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job='Contatos.ExclusaoService-read-http'}"
    }
   ]
  },
  {
   "title": "Persistência Service",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job='Contatos.PersistenciaService-read-http'}"
    }
   ]
  },
  {
   "title": "Consulta Service",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"Contatos.ConsultaService-read-http\"}"
    }
   ]
  },
  { "title": "Filas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Inclusão Service / Writes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_message_produced_total{job=\"Contatos.CadastroService-read-http\"}"
    }
   ]
  },
  {
   "title": "Alteração Service / Reads",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_message_produced_total{job=\"Contatos.AlteracaoService-read-http\"}"
    }
   ]
  },
  {
   "title": "Exclusão Service / Writes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_message_produced_total{job=\"Contatos.ExclusaoService-read-http\"}"
    }
   ]
  },
  {
   "title": "Persistência Service / Reads",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_message_consumed_total{job=\"Contatos.PersistenciaService-read-http\"}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Consulta Service",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(controller, method) (http_requests_received_total{job=\"Contatos.ConsultaService-read-http\"})"
    }
   ]
  },
  {
   "title": "Inclusão Service",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(endpoint, method) (http_requests_received_total{job=\"Contatos.CadastroService-read-http\"})"
    }
   ]
  },
  {
   "title": "Exclusão Service",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(controller, method) (http_requests_received_total{job=\"Contatos.ExclusaoService-read-http\"})"
    }
   ]
  },
  {
   "title": "Alteração Service",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(controller, method) (http_requests_received_total{job=\"Contatos.AlteracaoService-read-http\"})"
    }
   ]
  },
  {
   "title": "Logs - Consulta Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "type": "logs",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "{Microservice=\"Contatos.ConsultaService\"} |= ``"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs - Inclusão Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "type": "logs",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "{Microservice=\"Contatos.CadastroService\"} |= ``"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs - Exclusão Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "type": "logs",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 62 },
     "targets": [
      {
       "expr": "{Microservice=\"Contatos.ExclusaoService\"} |= ``"
      }
     ]
    },
    {
     "type": "logs",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 76 },
     "targets": [
      {
       "expr": "{Microservice=\"Contatos.ConsultaService\"} |= ``"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs - Alteração Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "type": "logs",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 71 },
     "targets": [
      {
       "expr": "{Microservice=\"Contatos.AlteracaoService\"} |= ``"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs - Persistência Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "type": "logs",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 66 },
     "targets": [
      {
       "expr": "{Microservice=\"Contatos.PersistenciaService\"} |= ``"
      }
     ]
    }
   ]
  }
 ]
}