{
 "title": "Monitoramento de Serviços - Contatos",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Contatos.API",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job='Contatos.API-read-http'}"
    }
   ]
  },
  {
   "title": "Consulta Service",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"Contatos.ConsultaService-read-http\"}"
    }
   ]
  },
  {
   "title": "Cadastro Service",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job='Contatos.CadastroService-read-http'}"
    }
   ]
  },
  {
   "title": "Persistência Service",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job='Contatos.PersistenciaService-read-http'}"
    }
   ]
  },
  {
   "title": "Exclusão Service",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job='Contatos.ExclusaoService-read-http'}"
    }
   ]
  },
  { "title": "Filas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Cadastro Service / Writes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_message_produced_total{job=\"Contatos.CadastroService-read-http\"}"
    }
   ]
  },
  {
   "title": "Exclusão Service / Reads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_message_produced_total{job=\"Contatos.ExclusaoService-read-http\"}"
    }
   ]
  },
  {
   "title": "Persistência Service / Reads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_message_consumed_total{job=\"Contatos.PersistenciaService-read-http\"}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Cadastro Service",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(method, method) (http_requests_received_total{job=\"Contatos.CadastroService-read-http\"})"
    }
   ]
  },
  {
   "title": "Consulta Service",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(controller, method) (http_requests_received_total{job=\"Contatos.ConsultaService-read-http\"})"
    }
   ]
  },
  {
   "title": "Exclusão Service",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(controller, method) (http_requests_received_total{job=\"Contatos.ExclusaoService-read-http\"})"
    }
   ]
  },
  {
   "title": "Contatos.API",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 15, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(controller, method) (http_requests_received_total{job=\"Contatos.API-read-http\"})"
    }
   ]
  },
  {
   "title": "Logs - Contatos.API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "type": "logs",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "{Microservice=\"Contatos.API\"} |= ``"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs - Consulta Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "type": "logs",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "{Microservice=\"Contatos.ConsultaService\"} |= ``"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs - Cadastro Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "type": "logs",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "{Microservice=\"Contatos.CadastroService\"} |= ``"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs - Exclusão Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "type": "logs",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "{Microservice=\"Contatos.ExclusaoService\"} |= ``"
      }
     ]
    },
    {
     "type": "logs",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "{Microservice=\"Contatos.ConsultaService\"} |= ``"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs - Persistência Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "type": "logs",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "{Microservice=\"Contatos.PersistenciaService\"} |= ``"
      }
     ]
    }
   ]
  }
 ]
}