apiVersion: v1
kind: Service
metadata:
  name: contatos-cadastroservice-svc
  labels: # Definição de rótulos
    app: contatos-cadastroservice
    env: production
    group: servicos-de-api
    ms: cadastroservice
  annotations: # Definição de anotações
    description: "Este service é usado para o microsserviço de inclusão de contato"
    url: "http://localhost:31081/"
spec:
  selector:
    app: contatos-persistenciaservice-pod
  ports:
    - protocol: TCP
      port: 8081         # Porta interna que o Service expõe dentro do cluster
      targetPort: 8080   # Porta interna do container (a mesma da API)
      nodePort: 31081    # Porta no nó do Kubernetes para acesso externo (fora do cluster)
  type: NodePort        # Tipo de Service para expor a aplicação externamente