apiVersion: v1
kind: Pod
metadata:
  name: contatos-exclusaoservice-pod
  labels: # Definição de rótulos
    app: contatos-app
    env: production
    group: servicos-de-api
  annotations: # Definição de anotações
    description: "Este pod é usado para o microsserviço de exclusão de contato"
    url: "http://localhost:31084/"
spec:
  containers:
    - name: contatos-exclusaoservice-container
      image: rodrigocezarleao/contatos.exclusaoservice:v1
      ports:
        - containerPort: 8080 # Porta exposta pelo container