apiVersion: v1
kind: Service
metadata:
  name: contatos-exclusaoservice-svc
  labels: # Definição de rótulos
    app: contatos-app
    env: production
    group: servicos-de-api
    ms: exclusaoservice
  annotations: # Definição de anotações
    description: "Este service é usado para o microsserviço de exclusão de contato"
    url: "http://localhost:31084/"
spec:
  selector:
    app: contatos-app
  ports:
    - protocol: TCP
      port: 8084         # Porta interna que o Service expõe dentro do cluster
      targetPort: 8080   # Porta interna do container (a mesma da API)
      nodePort: 31084    # Porta no nó do Kubernetes para acesso externo (fora do cluster)
  type: NodePort        # Tipo de Service para expor a aplicação externamente