apiVersion: apps/v1
kind: Deployment
metadata:
  name: contatos-consultaservice-deployment
  labels:    
    app: contatos-consultadeployment
    env: production
    group: servicos-de-api
    ms: consultaservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contatos-consultaservice-pod
  template:
    metadata:
      labels:
        app: contatos-consultaservice-pod
    spec:
      containers:
      - name: contatos-consultaservice-container
        image: rodrigocezarleao/contatos.consultaservice:v2
        ports:
        - containerPort: 8080