apiVersion: v1
kind: Pod
metadata:
  name: contatos-consultaservice-pod
  labels: # Definição de rótulos
    app: contatos-app
    env: production
    group: servicos-de-api
  annotations: # Definição de anotações
    description: "Este pod é usado para o microsserviço de consulta de contato"
    url: "http://localhost:31082/"
spec:
  containers:
    - name: contatos-consultaservice-container
      image: rodrigocezarleao/contatos.consultaservice:v1
      ports:
        - containerPort: 8080 # Porta exposta pelo container