apiVersion: v1
kind: Pod
metadata:
  name: contatos-cadastroservice-pod
  labels: # Definição de rótulos
    app: contatos-app
    env: production
    group: servicos-de-api
    ms: cadastroservice
  annotations: # Definição de anotações
    description: "Este pod é usado para o microsserviço de inclusão de contato"
    url: "http://localhost:31081/"
spec:
  containers:
    - name: contatos-cadastroservice-container
      image: rodrigocezarleao/contatos.inclusaoservice:v1
      ports:
        - containerPort: 8080 # Porta exposta pelo container