apiVersion: apps/v1
kind: Deployment
metadata:
  name: contatos-exclusaoservice-deployment
  labels:
    app: contatos-exclusaodeployment
    env: production
    group: servicos-de-api
    ms: exclusaoservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contatos-exclusaoservice-pod
  template:
    metadata:
      labels:
        app: contatos-exclusaoservice-pod
    spec:
      containers:
      - name: contatos-exclusaoservice-container
        image: rodrigocezarleao/contatos.exclusaoservice:v2
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: contatos-exclusaoservice-svc
  labels: 
    app: contatos-exclusaoservice
    env: production
    group: servicos-de-api
    ms: exclusaoservice
  annotations: 
    description: "Este service é usado para o microsserviço de exclusão de contato"
    url: "http://localhost:31084/"
spec:
  selector:
    app: contatos-exclusaoservice-pod
  ports:
    - protocol: TCP
      port: 8084        
      targetPort: 8080  
      nodePort: 31084   
  type: NodePort        