apiVersion: v1
kind: Pod
metadata:
  name: contatos-persistenciaservice-pod
  labels: # Definição de rótulos
    app: contatos-app
    env: production
    group: servicos-de-api
    ms: persistenciaservice
  annotations: # Definição de anotações
    description: "Este pod é usado para o microsserviço de persistência de banco"
    url: "http://localhost:31085/"
spec:
  containers:
    - name: contatos-persistenciaservice-container
      image: rodrigocezarleao/contatos.persistenciaservice:v2
      ports:
        - containerPort: 8080 # Porta exposta pelo container