apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
  labels:
    app: grafana
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        orgId: 1
        url: http://loki-svc.default.svc.cluster.local:3100
        basicAuth: false
        isDefault: true
        version: 1
        editable: false
      - name: Prometheus
        type: prometheus
        access: proxy
        orgId: 1
        url: http://prometheus-service.default.svc.cluster.local:9090
        basicAuth: false
        isDefault: false
        version: 1
        editable: false

  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: 'Default'
        orgId: 1
        folder: ''
        type: file
        options:
          path: /var/lib/grafana/dashboards
