apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-pv
  labels:
    app: loki
spec:
  capacity:
    storage: 1Gi  # Ajuste o tamanho do volume conforme necessário
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/loki  # Caminho no nó, pode ser alterado conforme sua infraestrutura
