apiVersion: v1
kind: Service
metadata:
  name: loki-svc
spec:
  selector:
    app: loki  # Este seletor deve corresponder à label do Deployment
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100  # Porta interna no container
      nodePort: 30100
  type: NodePort
