apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-pvc
  namespace: default  # Especifique o namespace apropriado
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Ajuste o tamanho conforme necessário
  storageClassName: standard
