apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver-pod
  template:
    metadata:
      labels:
        app: sqlserver-pod
    spec:
      containers:
      - name: sqlserver
        image: mcr.microsoft.com/azure-sql-edge
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          value: "Grupo#31"
        - name: MSSQL_PID
          value: "Developer"
        volumeMounts:
        - mountPath: /var/opt/mssql
          name: mssql-data
      volumes:
      - name: mssql-data
        persistentVolumeClaim:
          claimName: mssql-pvc
