apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver-deployment
  labels:
    app: sqlserver-dpl
    env: production
    group: servicos-gerais
    ms: sqlserver
  annotations:
    description: "Este deployment é usado para o banco de dados"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
        - name: sqlserver
          image: mcr.microsoft.com/azure-sql-edge  # Imagem do SQL Server para Kubernetes
          ports:
            - containerPort: 1433  # Porta do SQL Server
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              value: "Grupo#31"  # Defina uma senha segura
            - name: MSSQL_PID
              value: "Developer"
      volumes:
        - name: sqlserver-config
          configMap:
            name: sqlserver-config
            items:
              - key: sqlserver.conf
                path: sqlserver.conf
        - name: sqlserver-init
          configMap:
            name: sqlserver-config
            items:
              - key: init.sql
                path: init.sql
