apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlserver-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Define que o volume será montado com leitura e escrita em um único pod
  resources:
    requests:
      storage: 1Gi  # Solicita 10 GB de armazenamento
  storageClassName: manual  # Nome da StorageClass, deve ser o mesmo que o do PV
