apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlserver-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Modo de acesso
  resources:
    requests:
      storage: 1Gi  # Solicitação de armazenamento
