apiVersion: v1
kind: Service
metadata:
  name: sqlserver-svc
  labels: # Definição de rótulos
    app: sqlserver-service
    env: production
    group: servicos-gerais
    ms: sqlserver
  annotations: # Definição de anotações
    description: "Este service é usado para o banco de dados"
spec:
  selector:
    app: sqlserver-pod    # tem que ser o mesmo das apis
  ports:
    - protocol: TCP
      port: 1433        # Porta do Service
      targetPort: 1433  # Porta do container
      nodePort: 31433   # Porta exposta no nó (opcional, será escolhida automaticamente se não especificado)
  type: NodePort        # Exposição externa
