apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver-deployment
  labels:
    app: sqlserver-dpl
    env: production
    group: servicos-gerais
    ms: sqlserver
  annotations:
    description: "Este deployment é usado para o banco de dados"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver-pod
  template:
    metadata:
      labels:
        app: sqlserver-pod
    spec:
      containers:
        - name: sqlserver
          image: mcr.microsoft.com/azure-sql-edge
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              value: "Grupo#31"
            - name: MSSQL_PID
              value: "Developer"
          # volumeMounts:
          #   - name: sqlserver-entrypoint
          #     mountPath: /opt/sqlserver-entrypoint.sh
          #     subPath: entrypoint.sh
          #   - name: sqlserver-init
          #     mountPath: /mnt/data/sqlserver
          #     subPath: init.sql
          # command: ["/bin/bash", "/opt/sqlserver-entrypoint.sh"]
      volumes:
        - name: sqlserver-storage  # Nome do volume montado
          persistentVolumeClaim:
            claimName: sqlserver-pvc  # PVC que será utilizado para o volume persistente
