apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver-deployment
  labels:
    app: sqlserver-dpl
    env: production
    group: servicos-gerais
    ms: sqlserver
  annotations:
    description: "Este deployment é usado para o banco de dados"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver-pod
  template:
    metadata:
      labels:
        app: sqlserver-pod
    spec:
      containers:
      - name: sqlserver
        image: mcr.microsoft.com/azure-sql-edge
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          value: "Grupo#31"
        - name: MSSQL_PID
          value: "Developer"
        volumeMounts:
        - mountPath: /var/opt/mssql
          name: mssql-data
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
          readOnly: true
        command:
        - /bin/bash
        - -c
        - |
          /opt/mssql/bin/sqlservr & sleep 20 && \
          /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Grupo#31 -i /docker-entrypoint-initdb.d/init.sql && \
          tail -f /dev/null
      volumes:
      - name: mssql-data
        persistentVolumeClaim:
          claimName: mssql-pvc
      - name: init-script
        configMap:
          name: init-sql-config
