# Base image for the runtime environment
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8081

# Build image for compiling the code
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["./Contatos.CadastroService.csproj", "Contatos.CadastroService/"]
RUN dotnet restore "./Contatos.CadastroService/Contatos.CadastroService.csproj"
WORKDIR "/src/Contatos.CadastroService"
COPY . .
RUN dotnet build "./Contatos.CadastroService.csproj" -c $BUILD_CONFIGURATION -o /app/build

# Publish image for creating the final application
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./Contatos.CadastroService.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# Final image for running the application
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Contatos.CadastroService.dll"]