name: Build and Publish

on:
  workflow_dispatch:
  # push:
     #branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4   
   
    - uses: docker/setup-buildx-action@v3.4.0 
